<?php

namespace AppBundle\Repository;

/**
 * coursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coursesRepository extends \Doctrine\ORM\EntityRepository
{
}
